### PR TITLE
GeoBoundingBox limits

### PR DESCRIPTION
**Pull request by turnerm**
Addresses #92. 

I wanted to check with you: I've now made it that south also cannot be equal to north (and west not equal to east). For the limits I've allowed the bounds to be included. Do you think these are the right choices?

### CODE REVIEW

**Comment by turnerm** [comment]
@Tinkaa thanks so much for taking a look!

> I think we should allow North==South, this would imo just indicating only retrieving that one lon/lat. What is your reasoning for only allowing >?

I figured that if you have North == South you have a line, not a box, not sure what the use case could be. 

> to me the names north, south, west, east, are getting more and more confusing. As you could also interpret it as being on the west vs east hemisphere. Would it be an idea to instead use max_lat, min_lat, max_lon, min_lon? Maybe I am nitpicking too much here though.

That's a great idea, I will change them!

**Comment by Tinkaa** [comment]
>I figured that if you have North == South you have a line, not a box, not sure what the use case could be.
Yes agree you have a line and dont kno a use case either. But theoretically I think we should allow downloading a line.

**Comment by turnerm** [comment]
> Yes agree you have a line and dont kno a use case either. But theoretically I think we should allow downloading a line.

Alright, done!

I've also changed the parameter names as you suggested. My last question for you @Tinkaa is this: do you think the string representations still make sense in light of this change? By that I mean the `__repr__`  and `get_filename_repr` methods

**Comment by Tinkaa** [comment]
Hmm things are always more complex than you think. 

But I think it still makes sense to have the two functionalities and cannot come up with better naming so yeah would say we leave those.

**Review by Tinkaa — APPROVED** [review]

**Pull request merged**
