### PR TITLE
Add warnings to USGS NDVI data, addresses #150

### PR DESCRIPTION
**Pull request by caldwellst**
Addresses adding warnings based on #150.

### CODE REVIEW

**Review by turnerm — COMMENTED** [review]
Looks great! My only comment would be that in CHRIPS and now also GloFAS, we don't just give a warning with an out of bounds date, but throw an error. Not sure if you think it's worth being consistent across these. (Open to changing CHIRPS and GloFAS if you think warning is the better way to go)

**Comment by caldwellst** [comment]
Ooh that's an interesting point. I think that could be a good option here as well. I think the only potential annoyance to users is that for dekadal or pentadal data, it's a bit less clear where the bounds are. They might just want everything up to a certain date but just specify to end of year to make sure they don't miss a specific time or dekad?  So like, where do we set the "bounds" in this instance? Last day of the last available dekad?

**Comment by caldwellst** [comment]
@turnerm @castledan Thoughts?

**Comment by castledan** [comment]
What happens in the code now? Do you raise a warning and adjust the end date to the last available one?

**Comment by caldwellst** [comment]
Ah, so I'm realising a bit of an artifact of the NDVI data, but there are random dekads missing from the data in the online portal due to random errors from the sensor. Because of this, I couldn't throw an error if dekadal data unavailable, but simply log it in info that no data available for that year and dekad. Now I throw an explicit warning if the end date is past a certain point since there's more systematic missing data, but just keep the end date to avoid hardcoding anything and allow the logging info pass on messages about data not available.

**Pull request merged**
